version: "3.8"
services:
  postgres:
    build: ./database
    environment:
      - POSTGRES_PASSWORD=myGreatPassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres
    ports:
      - "6969:80"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules/
    depends_on:
      - postgres
    ports:
      - "80:8080"
volumes:
  db_data: