FROM ubuntu:latest

ARG environment
ENV TZ=Europe/Warsaw \
    DEBIAN_FRONTEND=noninteractive

# Install apache, PHP, and supplimentary programs.
RUN apt-get update && apt-get -y upgrade
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:ondrej/php

RUN apt-get -y install \
    apache2 \
    php8.1 \
    php-pgsql \
    libapache2-mod-php8.1 \
    curl \
    php-curl \
    nano \
    php8.1-xml \
    php-zip \
    php-bcmath \
    php-tokenizer \
    php-mbstring \
    php8.1-common \
    php-gd \
    php-cli \
    git \
    cron

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Enable apache mods.
RUN a2enmod php8.1
RUN a2enmod rewrite
RUN a2enmod ssl

RUN a2ensite default-ssl

# Update the PHP.ini file, enable <? ?> tags and quieten logging.
RUN sed -i "s/short_open_tag = Off/short_open_tag = On/" /etc/php/8.1/apache2/php.ini
RUN sed -i "s/error_reporting = .*$/error_reporting = E_ERROR | E_WARNING | E_PARSE/" /etc/php/8.1/apache2/php.ini

# Manually set up the apache environment variables
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

# Expose ports for apache server
EXPOSE 443
EXPOSE 80

# Update the default apache site
ADD apache-config.conf /etc/apache2/sites-enabled/000-default.conf

# From now on, work in website directory
WORKDIR /var/www/html

# Add only composer files to run composer as a separate step from following ones
ADD composer.json composer.lock /var/www/html/
RUN composer install --no-scripts --no-autoloader

# Copy all project content
ADD . /var/www/html

RUN chown -R www-data:www-data .

# Autoloader and composer scripts
RUN composer dump-autoload --optimize

# RUN php artisan lang:js --no-lib resources/js/lang/messages.js

# RUN npm run ${environment}

# Run apache
CMD /usr/sbin/apache2ctl -D FOREGROUND